services:
  postgres-barber-services:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5433:5433"
    volumes:
      - postgres-barber-services-volume:/var/lib/postgresql/data
    restart: always

  api:
    container_name: api-barber-services
    build: .
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - postgres-barber-services
    env_file:
      - .env

volumes:
  postgres-barber-services-volume:


